version: "3.7"
services:
  # mysql数据库
  db:
    image: summychoutoto/mysql:5.7-support-logs-and-socket
    hostname: mysql_server
    ports:
      - 13306:3306
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # 在宿主机文件"/etc/passwd"中找出目标"uid:gid"
    user: 1002:1003
    environment:
      MYSQL_ROOT_PASSWORD: "Pwd123Pwd"
      MYSQL_USER: "alice"
      MYSQL_PASSWORD: "Pwd123Pwd123"
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo
      - ~/fotolei-pssa-db/data:/var/lib/mysql
      - ~/fotolei-pssa-db/logs:/var/log/mysql
      - ~/fotolei-pssa-db/conf.d:/etc/mysql/mysql.conf.d
      - ~/fotolei-pssa-db/migrations:/mysql/migrations
    networks:
      - mysql_service_network

networks:
  mysql_service_network:
    external: true
